apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{.Namespace}}
resources:
- ../../base
- ingress.yaml
- secrets.yaml
images:
- name: IMAGE
  newName: {{.DefaultImageName}}
  newTag: {{.DefaultImageTag}}

patches:
- path: replicas-patch.yaml
