apiVersion: v1
kind: Service
metadata:
  name: {{.ApplicationName}}
  labels:
    app: {{.ApplicationName}}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{.ApplicationPort}}
  selector:
    app: {{.ApplicationName}}