apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecr-renew
rules:
- apiGroups: [""]
  resources: ["secrets", "serviceaccounts"]
  verbs:
  - create
  - update
  - patch
  - delete
  - get
  - list