---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: direct-chain
spec:
  chain:
    middlewares:
      - name: replace-path-middleware
      - name: cors-headers-middleware