apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- middleware-auth-ad.yaml
- middleware-cors-headers.yaml
- middleware-redirect-https.yaml
- chain-secure.yaml
- chain-direct.yaml