apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: aws-credential
spec:
  type: kv-v2
  mount: tools
  path: shared/aws-credential
  destination:
    name: aws-credential
    create: true
  refreshAfter: 30s